name: Compare Master DLPerf

on:
  schedule:
    - cron: '10 20 * * *'
  workflow_dispatch:
    inputs:
      branch_name:
        description: "branch_name"
        default: "master"
        required: false
      compare_max_day:
        description: "compare_max_day"
        default: "1"
        required: false
      memory_interval:
        description: "memory_interval"
        default: "50"
        required: false
      throughput_interval:
        description: "throughput_interval"
        default: "50"
        required: false

jobs:
  test_result:
    name: Get Master DLPerf Test Result
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout OneFlow Test
        uses: actions/checkout@v2
      - name: Get Master DLPerf Test Result
        id: get-master-dlperf-test-result
        env:
          compare_max_day: ${{ github.event.inputs.compare_max_day }}
          throughput_interval: ${{ github.event.inputs.throughput_interval }}
          branch_name: ${{ github.event.inputs.branch_name }}
          memory_interval: ${{ github.event.inputs.memory_interval }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        run: |
          set -x
          compare_max_day=${compare_max_day:-1}
          memory_interval=${memory_interval:-"50"}
          branch_name=${branch_name:-"master"}
          throughput_interval=${throughput_interval:-"50"}
          today_date=$(date "+%Y%m%d")
          curl http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64 -o $HOME/ossutil64
          chmod 755 $HOME/ossutil64
          $HOME/ossutil64 config -e oss-cn-beijing.aliyuncs.com -i ${OSS_ACCESS_KEY_ID} -k ${OSS_ACCESS_KEY_SECRET}  -L EN -c $HOME/.ossutilconfig
          $HOME/ossutil64 cp -r oss://oneflow-test/OneBrain/commit/${branch_name}/${today_date} ./  --include "*dlperf*.json"
          compare_date=$(date -d "${compare_max_day} day ago" +%Y%m%d)
          if [ ! -d "/${today_date}" ]; then
            for (( j=1; j<=$compare_max_day; j++ ))
            do
              compare_date=$(date -d "${j} day ago" +%Y%m%d)
              $HOME/ossutil64 cp -r oss://oneflow-test/OneBrain/commit/${branch_name}/${compare_date} ./  --include "*dlperf*.json"
              if [ ! -d "/${compare_date}" ]; then
                break
              fi
            done
            if [ ! -d "/${compare_date}" ]; then
              echo "get_result=1" >> $GITHUB_ENV
              python3 ./compare/dlperf.py --current-log ./${today_date} --history-log ./${compare_date} --memory-interval ${memory_interval} --throughput-interval ${throughput_interval}
              all_test_result_md=./${today_date}/compare_master_dlperf_result.md
              issue_title=$(date "+%Y%m")
              echo "issue_title=${issue_title}_OneFlow_Compare_Master_DLPerf_Test_Result" >> $GITHUB_ENV
              echo "issue_comment_body=""${all_test_result_md}" >> $GITHUB_ENV
            fi
          fi
      - name: Create Issue Comment
        if: env.get_result == '1'
        uses: ./.github/actions/issue
        with:
          issue_title: ${{ env.issue_title }}
          issue_comment_body: ${{ env.issue_comment_body }}         
